export enum EVENT {
    CHAIN_ID_CHANGED = 'CHAIN_ID_CHANGED',
    ACCOUNT_CHANGED = 'ACCOUNT_CHANGED',
    RELOAD_ALLOWANCE = 'RELOAD_ALLOWANCE',
    OPEN_LOGIN_ALERT_MODAL = 'OPEN_LOGIN_ALERT_MODAL',
    OPEN_WALLET_CONNECT_MODAL = 'OPEN_WALLET_CONNECT_MODAL',
    WALLET_CONNECTED = 'WALLET_CONNECTED',
    REVALIDATE_TX_DATA = 'REVALIDATE_TX_DATA',
    OPEN_POPUP_TRANSACTIONS = 'OPEN_POPUP_TRANSACTIONS',
    SIGNING_CONNECT_WALLET_MESSAGE = 'SIGNING_CONNECT_WALLET_MESSAGE',
    DISCONNECT = 'DISCONNECT',
  }
  