export * from './atoms'
export * from './basics'
export * from './fonts'

export interface IResume {
  id: string
  shortId: string
  name: string
  slug: string
  basics: any
  sections: any
  metadata: any
  isPublic: boolean
  createdAt: Date
}

enum FONT_CATEGORY {
  DISPLAY = 'display',
  HANDWRITING = 'handwriting',
  MONOSPACE = 'monospace',
  SANS_SERIF = 'sans-serif',
  SERIF = 'serif',
}

export type Font = {
  family: string
  variants: string[]
  subsets: string[]
  version: string
  lastModified: string
  files: Record<string, string>
  category: FONT_CATEGORY
  kind: string
}

export enum BUCKET {
  TMP = 'TMP',
  UPLOADS = 'UPLOADS',
  ASSETS = 'ASSETS',
  AVATARS = 'AVATARS',
  THUMBNAILS = 'THUMBNAILS',
}

export enum CONTRACT {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  ITERN = 'ITERN',
  REMOTE = 'REMOTE',
}

export enum EXPERIENCE {
  NO_EXPERIENCE = 'NO_EXPERIENCE',
  UNDER_ONE_YEAR = 'UNDER_ONE_YEAR',
  ONE_YEAR = 'ONE_YEAR',
  TWO_YEARS = 'TWO_YEARS',
  THREE_YEARS = 'THREE_YEARS',
  FOUR_YEARS = 'FOUR_YEARS',
  FIVE_YEARS = 'FIVE_YEARS',
  OVER_YEARS = 'OVER_YEARS',
}

export enum RANK {
  INTERN = 'INTERN',
  STAFF = 'STAFF',
  LEADER = 'LEADER',
  SUB_MANAGER = 'SUB_MANAGER',
  MANAGER = 'MANAGER',
}

export enum FIELD_ACTIVITY {
  IT_SOFTWARE = 'IT_SOFTWARE',
  MARKETING = 'MARKETING',
  ACCOUNTING_AUDITING = 'ACCOUNTING_AUDITING',
  LAW = 'LAW',
  INSURANCE = 'INSURANCE',
  REAL_ESTATE = 'REAL_ESTATE',
  PHARMACEUTICAL_MEDICAL_BIOTECHNOLOGY = 'PHARMACEUTICAL_MEDICAL_BIOTECHNOLOGY',
  INTERNET_ONLINE = 'INTERNET_ONLINE',
  MARKETING_COMMUNICATION_ADVERTISING = 'MARKETING_COMMUNICATION_ADVERTISING',
  RESTAURANT_HOTEL = 'RESTAURANT_HOTEL',
  PRINTING_PUBLICATION = 'PRINTING_PUBLICATION',
  RENTAIL_CONSUMER_GOODS_FMCG = 'RENTAIL_CONSUMER_GOODS_FMCG',
  MANUFACTURE = 'MANUFACTURE',
  STOCK = 'STOCK',
  BUILD = 'BUILD',
  BANK = 'BANK',
  PERSONNEL = 'PERSONNEL',
  ARCHITECTURE_DESIGN = 'ARCHITECTURE_DESIGN',
  ENVIRONMENT = 'ENVIRONMENT',
  IMPORT_EXPORT = 'IMPORT_EXPORT',
  MAINTENANCE_REPAIR = 'MAINTENANCE_REPAIR',
  ELECTRONIC_REFRIGERATION = 'ELECTRONIC_REFRIGERATION',
  FASHION = 'FASHION',
  MECHANICAL = 'MECHANICAL',
  ADVISE = 'ADVISE',
  TELECOMMUNICATION = 'TELECOMMUNICATION',
  EDUCATIONS = 'EDUCATIONS',
  ECOMMERCE = 'ECOMMERCE',
  LOGISTICS_TRANSPORTATION = 'LOGISTICS_TRANSPORTATION',
  NON_PROFIT_ORGANIZATION = 'NON_PROFIT_ORGANIZATION',
  STATE_AGENCIES = 'STATE_AGENCIES',
  TOURISM = 'TOURISM',
  AUTOMATION = 'AUTOMATION',
  AGENCY_DESIGN_DEVELOPER = 'AGENCY_DESIGN_DEVELOPER',
  AGENCY_MARKETING_ADVERTISING = 'AGENCY_MARKETING_ADVERTISING',
  ENERGY = 'ENERGY',
  ENTERTAINMENT = 'ENTERTAINMENT',
  IT_HARDWARE = 'IT_HARDWARE',
  AGRICULTURE_FORESTRY_FISHERY = 'AGRICULTURE_FORESTRY_FISHERY',
  FINANCE = 'FINANCE',
  OTHER = 'OTHER',
}

export enum SALARY {
  UNDER_THREE_MILLION = 'dưới 3 triệu',
  THREE_TO_FIVE_MILLION = '3 - 5 triệu',
  FIVE_TO_SEVEN_MILLION = '5 - 7 triệu',
  SEVEN_TO_TEN_MILLION = '7 - 10 triệu',
  TEN_TO_TWELVE_MILLION = '10 - 12 triệu',
  TWELVE_TO_FIFTEEN_MILLION = '12 - 15 triệu',
  FIFTEEN_TO_TWENTY_MILLION = '15 - 20 triệu',
  TWENTY_TO_TWENTY_FIVE_MILLION = '20 - 25 triệu',
  TWENTY_FIVE_TO_THIRTY_MILLION = '25 - 30 triệu',
  OVER_THIRTY_MILLION = 'Trên 30 triệu',
  DEAL = 'Deal',
}

export enum JOB {
  WORK_SAFETY = 'WORK_SAFETY',
  TECHNICAL_SALES = 'TECHNICAL_SALES',
  RETAIL_WHOLESALE = 'RETAIL_WHOLESALE',
  PRESS_TELEVISION = 'PRESS_TELEVISION',
  INSURANCE = 'PRESS_TELEVISION',
  MAINTENANCE_REPAIR = 'MAINTENANCE_REPAIR',
  REAL_ESTATE = 'REAL_ESTATE',
  TRANSLATOR_INTERPRETER = 'TRANSLATOR_INTERPRETER',
  POST_AND_TELECOMMUNICATIONS = 'POST_AND_TELECOMMUNICATIONS',
  STOCKS_GOLD_FOREIGN_CURRENCY = 'STOCKS_GOLD_FOREIGN_CURRENCY',
  MECHANICAL_MANUFATURING_AUTOMATION = 'MECHANICAL_MANUFATURING_AUTOMATION',
  HIGH_TECHNOLOGY = 'HIGH_TECHNOLOGY',
  CAR_TECHNOLOGY = 'CAR_TECHNOLOGY',
  INFORMATION_TECHNOLOGY = 'CAR_TECHNOLOGY',
  PETROLEUM_CHEMICAL = 'PETROLEUM_CHEMICAL',
  TEXTILE_FOOTWARE = 'TEXTILE_FOOTWARE',
  GEOLOGY_MINERALS = 'GEOLOGY_MINERALS',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  ELECTRICAL_ELECTRONICS_REFRIGERATION = 'ELECTRICAL_ELECTRONICS_REFRIGERATION',
  ELECTRONIC_AND_TELECOMMUNICATIONS = 'ELECTRONIC_AND_TELECOMMUNICATIONS',
  TOURISM = 'TOURISM',
  PHARMACEUTICAL_BIOTECHNOLOGY = 'PHARMACEUTICAL_BIOTECHNOLOGY',
  EDUCATION = 'EDUCATION',
  HIGH_END_GOODS = 'HIGH_END_GOODS',
  HOUSEHOLD_APPLIANCES = 'HOUSEHOLD_APPLIANCES',
  SHIPPING = 'SHIPPING',
  AIR = 'AIR',
  CONSUMER_GOODS = 'CONSUMER_GOODS',
  OFFICE_ADMINISTRATION = 'OFFICE_ADMINISTRATION',
  CHEMISTRY_BIOLOGY = 'CHEMISTRY_BIOLOGY',
  PLANNING_PROJECTS = 'PLANNING_PROJECTS',
  PRINTING_PUBLICATION = 'PRINTING_PUBLICATION',
  IT_HARDWARE_NETWORK = 'IT_HARDWARE_NETWORK',
  IT_SOFTWARE = 'IT_SOFTWARE',
  ACCOUNTING_AND_AUDITING = 'ACCOUNTING_AND_AUDITING',
  HOTEL_RESTAURANT = 'HOTEL_RESTAURANT',
  ARCHITECHTURE = 'ARCHITECHTURE',
  BUSINESS_SALES = 'BUSINESS_SALES',
  LOGISTICS = 'LOGISTICS',
  LAW_LEGAL = 'LAW_LEGAL',
  MARKETING_COMMUNICATION_ADVERTISING = 'MARKETING_COMMUNICATION_ADVERTISING',
  ENVIRONMENT_WASTE_TREATMENT = 'ENVIRONMENT_WASTE_TREATMENT',
  COSMETICS_JEWELRY = 'COSMETICS_JEWELRY',
  FINE_ARTS_ART_CINEMA = 'FINE_ARTS_ART_CINEMA',
  FINANCIAL_BANKING = 'FINANCIAL_BANKING',
  NGO_NON_GORVERNMENT_NON_PROFIT = 'NGO_NON_GORVERNMENT_NON_PROFIT',
  PERSONNEL = 'PERSONNEL',
  AGRICULTURE_FORESTRY_FISHERY = 'AGRICULTURE_FORESTRY_FISHERY',
  NON_GORVERNMENT_NON_PROFIT = 'NON_GORVERNMENT_NON_PROFIT',
  QUANLITY_MANAGEMENT = 'QUANLITY_MANAGEMENT',
  EXECUTIVE_MANAGEMENT = 'EXECUTIVE_MANAGEMENT',
  PRODUCT_OF_INDUSTRY = 'PRODUCT_OF_INDUSTRY',
  MANUFACTURE = 'MANUFACTURE',
  SPA_BEAUTY = 'SPA_BEAUTY',
  FINANCE_INVESTMENT = 'FINANCE_INVESTMENT',
  GRAPHIC_DESIGN = 'GRAPHIC_DESIGN',
  INTERIOR_DESIGN = 'INTERIOR_DESIGN',
  FASHION = 'FASHION',
  SCERETARY_ASSISTANTS = 'SCERETARY_ASSISTANTS',
  FOOD_DRINKS = 'FOOD_DRINKS',
  EVENTS_GIFTS = 'EVENTS_GIFTS',
  ADVISE = 'ADVISE',
  TRANSPORT_LOGISTICS = 'TRANSPORT_LOGISTICS',
  BUILD = 'BUILD',
  IMPORT_AND_EXPORT = 'IMPORT_AND_EXPORT',
  MEDICAL_PHARMACY = 'MEDICAL_PHARMACY',
  OTHER = 'OTHER',
}
